### ISSUE TITLE
matlab 2010, bottom gaussian fitting

### ISSUE THREAD

**Issue by chhuang48202** [LobanovaEG-LobanovSV/Q-HIU#1]
Your BGF method is very interesting, but using MatLab 2010 run your code, get a lot of error, and not working.

In your paper, equation (7), (8) and (9), you have A and u. When you change the vj, A and u are still the same or not? You have an example:

"The amplitudes, STDs, and expected values for the ten Raman-like bands were randomly selected from the intervals (0; 1), (5; 20) cm􀀀1, and (370; 1783) cm􀀀1, respectively."

If you use the same A and u, then the STD should already be fixed because your equation (8) has only three variables.  If you use different A and u, how do you connect these different gaussian curves?

How do you choose vi and vk so that they are not within the peak area?

Thanks!

Changhe Huang

**Comment by LobanovaEG-LobanovSV** [comment]
Hi Changhe,

Thank you for your comment.

I think the errors appeared during the drawing procedure. I have modified it now and uploaded new versions. Could you please download the new version and let me know if it still does not work? 

Regarding equations (7)-(9), the amplitude A and expected value u are the same when vj is changed. They are modified only when vi and vk are changed. Note also that vi must be an internal point of the interval (vi, vk).

Actually, the sentence “The amplitudes, STDs, and expected values for the ten Raman-like bands…” is not an example of using of Eqs. (7)-(9), but rather an example of artificial Raman spectra, which is used to test Eqs. (7)-(9). I have added a MATLAB script “Example_Fig_1B.m” which demonstrates it in more details. It should give a figure similar to the figure 1B from the paper.

Regarding the last questions, the variables vi and vk are varied along the whole region v, i.e. there can be three loops:

1st loop: `i = 1:N-2`
2nd loop: `k = i+2:N`
	Find A and mu using v_i, v_k, I_i, and I_k, i.e. solve Eqs. (9).
3rd loop: `j = i:k-1`
	Find G_j using amplitude A, expected value mu, and wavenumber v_j, i.e. calculate function Eq. (8).
	If G_j is smaller than I_j, than rewrite I_j by G_j.

Here, `N` is length of the vector v.

Note, that the loop over j is inside the loop over k. Similar, the loop over k is inside the loop over i.

I hope you will find it useful.

Kind regards,
Sergey

**Comment by chhuang48202** [comment]
Hi Sergey:


Thank you for the quick reply.


I will tell you the result soon.


Best regards,


Changhe Huang


________________________________

**Comment by skankhunt12138** [comment]
> Hi Changhe,
> 
> Thank you for your comment.
> 
> I think the errors appeared during the drawing procedure. I have modified it now and uploaded new versions. Could you please download the new version and let me know if it still does not work?
> 
> Regarding equations (7)-(9), the amplitude A and expected value u are the same when vj is changed. They are modified only when vi and vk are changed. Note also that vi must be an internal point of the interval (vi, vk).
> 
> Actually, the sentence “The amplitudes, STDs, and expected values for the ten Raman-like bands…” is not an example of using of Eqs. (7)-(9), but rather an example of artificial Raman spectra, which is used to test Eqs. (7)-(9). I have added a MATLAB script “Example_Fig_1B.m” which demonstrates it in more details. It should give a figure similar to the figure 1B from the paper.
> 
> Regarding the last questions, the variables vi and vk are varied along the whole region v, i.e. there can be three loops:
> 
> 1st loop: `i = 1:N-2`
> 2nd loop: `k = i+2:N`
> Find A and mu using v_i, v_k, I_i, and I_k, i.e. solve Eqs. (9).
> 3rd loop: `j = i:k-1`
> Find G_j using amplitude A, expected value mu, and wavenumber v_j, i.e. calculate function Eq. (8).
> If G_j is smaller than I_j, than rewrite I_j by G_j.
> 
> Here, `N` is length of the vector v.
> 
> Note, that the loop over j is inside the loop over k. Similar, the loop over k is inside the loop over i.
> 
> I hope you will find it useful.
> 
> Kind regards,
> Sergey

Hi Sergey,

Your reply helps me a lot in understanding your brilliant idea. Still something troubles me: to calculate the I_j using amplitude A and expected value mu we need three loops,which seems complex and time-consuming. However in your paper(2.3) it said it can be simply reduced to one loop. How did you achieve that?

BTW I am interested in your work about the algorithm. Have you been doing some research with respect to Raman microscopy lately? I'd like to know about it if you don't mind.

My regards,
Li
