### ISSUE TITLE
Example 2 syntax error

### ISSUE THREAD

**Issue by ghost** [LobanovaEG-LobanovSV/Q-HIU#2]
I received the following error when running Q-HIU following Example 2:

```
Iteration 1
SVD_ADC...
Error using  - 
Matrix dimensions must agree.

Error in corrcoef_S

Error in SVD_ADC

Error in Q_HIU (line 48)
    I =
    SVD_ADC(I0,Nx,Ny,R_thr_SVD,dx,dy,dnu,Save,Nu,DirIter,Names);
```

I am using MATLAB R2016a.  
Any help would be greatly appreciated!

**Comment by LobanovaEG-LobanovSV** [comment]
Hi Ernie,

Thank you for your comment and sorry for the delayed answer. I have modified the ‘corrcoef_S’ function - it is now also compatible with R2016a version. I hope you find it useful.

Best wishes,
Sergey
